application: jeenee-kr
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: main.app

- url: /_ah/queue/default
  script: task_def.app
