application: jeenee-kr
version: 2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /assets
  static_dir: assets

- url: /examples
  static_dir: examples

- url: /.*
  script: main.py


