application: handol
version: 1
runtime: python
api_version: 1
#threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /examples
  static_dir: examples

- url: /.*
  script: guestbook6_templates.py


